# Fetching the latest node image on apline linux
FROM node:20.10.0-alpine3.18

# Setting up the work directory
WORKDIR /usr/src/app

# Copying the package.json and yarn.lock files to the work directory
COPY package*.json yarn.lock ./

# Installing the dependencies
RUN yarn install

# Copying the rest of the files to the work directory
COPY . .

# Exposing the port
EXPOSE 3000

# Running the app
CMD ["yarn", "dev"]