version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: pledge-peak-backend:1.0.0
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/pledgepeak
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
    depends_on:
      - mongodb
    networks:
      - pledgepeak-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: pledge-peak-frontend:1.0.0
    depends_on:
      - backend
    networks:
      - pledgepeak-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Map port 80 on the host to port 80 in the container
      - "443:443" # Map port 443 on the host to port 443 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount any other necessary volumes (e.g., SSL certificates)
    depends_on:
      - backend
      - frontend

networks:
  pledgepeak-network:
    driver: bridge
