# Build stage
# Fetching the latest node image on apline linux
FROM node:20.10.0-alpine3.18 AS builder

# Setting up the work directory
WORKDIR /usr/src/app

# Copying the package.json and yarn.lock files to the work directory
COPY package*.json yarn.lock ./

# Installing the dependencies
RUN yarn install

# Copying the rest of the files to the work directory
COPY . .

# Building the app
RUN yarn build

# Production stage
FROM nginx:alpine3.18

# Copy built assets from builder stage to nginx public folder
COPY --from=builder /app/.next/static /usr/share/nginx/html/_next/static

# Copy nginx configuration
COPY ../nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Expose port 443
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
